apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/user-service.yaml
  - base/order-service.yaml
  - base/payment-service.yaml
  - base/notification-service.yaml
patchesStrategicMerge:
  - replicas.yaml
images:
  - name: user-service
    newTag: prod
  - name: order-service
    newTag: prod
  - name: payment-service
    newTag: prod
  - name: notification-service
    newTag: prod